[build-system]
requires = ["setuptools>=65.3.0", "wheel>=0.37.1"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [
  "tests",
]
pythonpath = [
  "src/kektris",
]
addopts = [
    "--import-mode=importlib",
]